#!/bin/sh
echo ""
echo "NLP Setup"
echo ""
echo "$( dirname -- "${BASH_SOURCE[0]}" )"
echo "Installing Python Packages:"

pip install flask detoxify langdetect nltk textblob spacy
# python3 -m textblob.download_corpora

echo "Done: NLP Setup"